version: '3.7'

services:
  database_c-car:
    image: postgres

    restart: always

    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@th
      - POSTGRES_DB=c-car

  app:
    container_name: c-car

    build: .

    links:
      - database_c-car

    restart: always

    ports:
      - 3333:3333

    volumes:
      - .:/usr/app

    depends_on:
      - database_c-car
