version: '3.7'

services:
  database_c-car:
    image: postgres

    restart: always

    ports:
      - 5432:5432

    volumes:
      - pg_database:/data/postegres

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@th
      - POSTGRES_DB=c-car

    network_mode: host

  app:
    container_name: c-car

    build: .

    network_mode: host

    ports:
      - 3333:3333

    volumes:
      - .:/usr/app

    depends_on:
      - database_c-car

volumes:
  pg_database:
    driver: local
